### Eyal de Lara

## 2024

# Towards Reconfigurable Linearizable Reads
- id: arXiv:2404.05470v1  
  tags: 
  authors:
    - Myles Thiessen
    - Aleksey Panas
    - Guy Khazma
    - Eyal de Lara

# PathFS A File System for the Hierarchical Edge
- id: doi:10.1145/3642968.3654822
  title: "PathFS: A File System for the Hierarchical Edge"
  tags:
    - cloudpath

# Feasibility of a wearable self-management application for patients with COPD at home
- id: doi:10.1186/s12911-024-02461-y
  tags:
    - wearcopd

# Towards Multi-Stakeholder Clouds
- id: doi:10.1145/3638550.3641135
  tags:
  buttons:
    - type: slide
      text: Slides
      link: pub/mcloud_presentation.pdf 

# Enhancing modular application placement
- id: doi:10.1016/j.comcom.2024.01.002
  tags:


## 2023

# PulmoListener: Continuous Acoustic Monitoring of Chronic Obstructive Pulmonary Disease in the Wild
- id: doi:10.1145/3610889
  title: "PulmoListener: Continuous Acoustic Monitoring of Chronic Obstructive Pulmonary Disease in the Wild"
  buttons:
    - type: pdf
      link: pub/ubicomp2023.pdf
    - type: bibtex
      link: bibtex/pulmolistener.txt
  tags:
    - wearcopd

# PORTEND: A Joint Performance Model for Partitioned Early-Exiting DNNs
- id: doi:10.1109/ICPADS60453.2023.00330
  tags:

# Data Management Systems for the Hierarchical Edge
- id: doi:10.1145/3614214.3614218
  tags:
    - cloudpath

##2022
# Hindsight is 20/20: Retrospective Lessons for Conducting Longitudinal Wearable Sensing Studies
- id: doi:10.1109/PerComWorkshops53856.2022.9767385
  description: "<span style='color:#b523cf;'><b>Best Paper Award at PerFail 2022</b></span>"
  buttons:
    - type: pdf
      link: pub/hindsight_percom.pdf
    - type: video
      link: https://www.youtube.com/watch?v=XQXcqDWDeyA
    - type: bibtex
      link: bibtex/hindsight20-20.txt 
  tags: 
    - wearcopd

# JITServer: Disaggregated Caching JIT Compiler for the JVM in the Cloud (Extended Abstract)
- date: 2022-07-11
  title: "JITServer: Disaggregated Caching JIT Compiler for the JVM in the Cloud (Extended Abstract)"
  link: https://www.usenix.org/conference/atc22/presentation/khrabrov
  publisher: USENIX ATC'22
  authors:
    - Alexey Khrabrov
    - Marius Pirvu
    - Vijay Sundaresan
    - Eyal de Lara
  buttons:
    - type: pdf
      link: pub/words22-khrabrov.pdf
    - type: slide
      text: Slides
      link: slides/words22-khrabrov-slides.pdf
    - type: video
      link: https://www.youtube.com/watch?v=15fjgHxeT-g
    - type: bibtex
      link: bibtex/jitserver-extended.txt
  tags:
    - jitserver
### Gururaj Saileshwar

## 2024
#
# PrIDE: Achieving Secure Rowhammer Mitigation with Low-Cost In-DRAM Trackers
- id: doi:10.1109/ISCA59077.2024.00087
  authors:
    - Aamer Jaleel
    - Gururaj Saileshwar
    - Stephen W. Keckler
    - Moinuddin Qureshi
  buttons:
    - type: source
      text: Code
      link: https://github.com/gururaj-s/PrIDE

## 2023
#
# PT-Guard: Integrity-Protected Page Tables to Defend Against Breakthrough Rowhammer Attacks
- id: doi:10.1109/DSN58367.2023.00022
  buttons:
    - type: slide
      text: Slides
      link: https://gururaj-s.github.io/assets/slides/DSN23_Saxena_slides.pptx
    - type: pdf
      text: PDF
      link: https://gururaj-s.github.io/assets/pdf/DSN23_Saxena.pdf

# Practical Timing Side-Channel Attacks on Memory Compression
- id: doi:10.1109/SP46215.2023.10179297
  buttons:
    - type: source
      text: Code
      link: https://github.com/IAIK/Memory-Compression-Attacks
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/SP23_Schwarzl.pdf

# SQUIP: Exploiting the Scheduler Queue Contention Side Channel
- id: doi:10.1109/SP46215.2023.10179368
  buttons:
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/SP23_Gast_slides.pdf
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/SP23_Gast.pdf        
        
# Scalable and Secure Row-Swap: Efficient and Safe Row Hammer Mitigation in Memory Systems
- id: doi:10.1109/HPCA56546.2023.10070999
  buttons:
    - type: source
      text: Code
      link: https://github.com/star-laboratory/scale-srs
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/woo2023rowswap_slides.ppsx
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/HPCA23_Woo.pdf
  description: "<span style='color:#b523cf;'><b>HPCA’23 Best Paper Award</b></span>"

## 2022
# AQUA: Scalable Rowhammer Mitigation by Quarantining Aggressor Rows at Runtime
- id: doi:10.1109/MICRO56248.2022.00022
  buttons:
    - type: source
      text: Code
      link: https://github.com/Anish-Saxena/aqua_rowhammer_mitigation
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/MICRO22_AQUA_slides.pptx
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/MICRO22_Saxena.pdf
      



### Nandita Vijaykumar
## 2024
# Photorealistic Object Insertion with Diffusion-Guided Inverse Rendering
- id: doi:10.48550/arXiv.2408.09702
  date: 2024-08-19

# Distributed Training of Neural Radiance Fields: A Performance Characterization
- id: doi:10.1109/ISPASS61541.2024.00044



### Niv Dayan
## 2024
# Memento Filter: A Fast, Dynamic, and Robust Range Filter
- id: arXiv:2408.05625

# Wayfinder: Speeding up Key-Value Separation by Avoiding I/O Based Indirection
- id: doi:10.1145/3663351.3663880

# Beyond Bloom: A Tutorial on Future Feature-Rich Filters.
- id: doi:10.1145/3626246.3654681

# Aleph Filter: To Infinity in Constant Time
- id: arXiv:2404.04703


### Bianca Schroeder
## 2024
# AUDIBLE: A Convolution-Based Resource Allocator for Oversubscribing Burstable Virtual Machines
- id: doi:10.1145/3620666.3651376

### Qizhen Zhang
## 2024
# DPDPU: Data Processing with DPUs
- id: arXiv:2407.13658 
   
# DDS: DPU-Optimized Disaggregated Storage
- id: doi:10.14778/3681954.3682002

# papers to remove from ORCID: bioRxiv versions of published papers

# motor cortex pre-print: uncomment once published in full
- id: doi:10.1101/2023.05.26.542452
  remove: true
  
- id: doi:10.1101/2022.08.30.505807
  remove: true

- id: doi:10.1101/2021.06.08.447507
  remove: true

- id: doi:10.1101/668962
  remove: true

- id: doi:10.1101/543678
  remove: true

- id: doi:10.1101/260992
  remove: true

- id: doi:10.1101/187948
  remove: true

- id: doi:10.1101/115485
  remove: true

- id: doi:10.1101/104562
  remove: true

- id: doi:10.1101/027102
  remove: true

- id: pmid:25819612
  remove: true
