### Eyal de Lara

## 2024

# Towards Reconfigurable Linearizable Reads
- id: arXiv:2404.05470v1  
  tags: 
  authors:
    - Myles Thiessen
    - Aleksey Panas
    - Guy Khazma
    - Eyal de Lara

# PathFS A File System for the Hierarchical Edge
- id: doi:10.1145/3642968.3654822
  title: "PathFS: A File System for the Hierarchical Edge"
  tags:
    - cloudpath

# Feasibility of a wearable self-management application for patients with COPD at home
- id: doi:10.1186/s12911-024-02461-y
  tags:
    - wearcopd

# Towards Multi-Stakeholder Clouds
- id: doi:10.1145/3638550.3641135
  tags:
  buttons:
    - type: slide
      text: Slides
      link: research/mcloud_presentation.pdf 

# Enhancing modular application placement
- id: doi:10.1016/j.comcom.2024.01.002
  tags:


## 2023

# PulmoListener: Continuous Acoustic Monitoring of Chronic Obstructive Pulmonary Disease in the Wild
- id: doi:10.1145/3610889
  title: "PulmoListener: Continuous Acoustic Monitoring of Chronic Obstructive Pulmonary Disease in the Wild"
  buttons:
    - type: pdf
      link: research/ubicomp2023.pdf
    - type: bibtex
      link: bibtex/pulmolistener.txt
  tags:
    - wearcopd

# PORTEND: A Joint Performance Model for Partitioned Early-Exiting DNNs
- id: doi:10.1109/ICPADS60453.2023.00330
  tags:

# Data Management Systems for the Hierarchical Edge
- id: doi:10.1145/3614214.3614218
  tags:
    - cloudpath

##2022
# JITServer: Disaggregated Caching JIT Compiler for the JVM in the Cloud (Extended Abstract)
- date: 2022-07-11
  title: "JITServer: Disaggregated Caching JIT Compiler for the JVM in the Cloud (Extended Abstract)"
  link: https://www.usenix.org/conference/atc22/presentation/khrabrov
  publisher: USENIX ATC'22
  authors:
    - Alexey Khrabrov
    - Marius Pirvu
    - Vijay Sundaresan
    - Eyal de Lara
  buttons:
    - type: pdf
      link: pub/words22-khrabrov.pdf
    - type: slide
      text: Slides
      link: slides/words22-khrabrov-slides.pdf
    - type: video
      link: https://www.youtube.com/watch?v=15fjgHxeT-g
    - type: bibtex
      link: bibtex/jitserver-extended.txt
  tags:
    - jitserver
### Gururaj Saileshwar

## 2024
#
# PrIDE: Achieving Secure Rowhammer Mitigation with Low-Cost In-DRAM Trackers
- id: doi:10.1109/ISCA59077.2024.00087
  authors:
    - Aamer Jaleel
    - Gururaj Saileshwar
    - Stephen W. Keckler
    - Moinuddin Qureshi
  buttons:
    - type: source
      text: Code
      link: https://github.com/gururaj-s/PrIDE

## 2023
#
# PT-Guard: Integrity-Protected Page Tables to Defend Against Breakthrough Rowhammer Attacks
- id: doi:10.1109/DSN58367.2023.00022
  buttons:
    - type: slide
      text: Slides
      link: https://gururaj-s.github.io/assets/slides/DSN23_Saxena_slides.pptx
    - type: pdf
      text: PDF
      link: https://gururaj-s.github.io/assets/pdf/DSN23_Saxena.pdf

# Practical Timing Side-Channel Attacks on Memory Compression
- id: doi:10.1109/SP46215.2023.10179297
  buttons:
    - type: source
      text: Code
      link: https://github.com/IAIK/Memory-Compression-Attacks
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/SP23_Schwarzl.pdf

# SQUIP: Exploiting the Scheduler Queue Contention Side Channel
- id: doi:10.1109/SP46215.2023.10179368
  buttons:
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/SP23_Gast_slides.pdf
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/SP23_Gast.pdf        
        
# Scalable and Secure Row-Swap: Efficient and Safe Row Hammer Mitigation in Memory Systems
- id: doi:10.1109/HPCA56546.2023.10070999
  buttons:
    - type: source
      text: Code
      link: https://github.com/star-laboratory/scale-srs
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/woo2023rowswap_slides.ppsx
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/HPCA23_Woo.pdf
  description: "<span style='color:#b523cf;'><b>HPCA’23 Best Paper Award</b></span>"

## 2022
# AQUA: Scalable Rowhammer Mitigation by Quarantining Aggressor Rows at Runtime
- id: doi:10.1109/MICRO56248.2022.00022
  buttons:
    - type: source
      text: Code
      link: https://github.com/Anish-Saxena/aqua_rowhammer_mitigation
    - type: slide
      link: https://gururaj-s.github.io/assets/slides/MICRO22_AQUA_slides.pptx
    - type: pdf
      link: https://gururaj-s.github.io/assets/pdf/MICRO22_Saxena.pdf
      



### Nandita Vijaykumar
## 2024
# Photorealistic Object Insertion with Diffusion-Guided Inverse Rendering
- id: doi:10.48550/arXiv.2408.09702
  date: 2024-08-19

# Distributed Training of Neural Radiance Fields: A Performance Characterization
- id: doi:10.1109/ISPASS61541.2024.00044



### Niv Dayan
## 2024
# Memento Filter: A Fast, Dynamic, and Robust Range Filter
- id: arXiv:2408.05625

# Wayfinder: Speeding up Key-Value Separation by Avoiding I/O Based Indirection
- id: doi:10.1145/3663351.3663880

# Beyond Bloom: A Tutorial on Future Feature-Rich Filters.
- id: doi:10.1145/3626246.3654681

# Aleph Filter: To Infinity in Constant Time
- id: arXiv:2404.04703




# Proteus: Preserving Model Confidentiality during Graph Optimizations
- id: arXiv:2404.12512
  
- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

      
# Strategy Tracker paper
- id: doi:10.7554/eLife.86491
  tags:
    - Bayesian
    - behaviour
  buttons:
    - type: package
      text: MATLAB toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_MATLAB
    - type: package
      text: Python toolbox
      link: https://github.com/Humphries-Lab/Bayesian_Strategy_Analysis_Python
    - type: data
      text: Y-maze data
      link: http://dx.doi.org/10.6080/K0KH0KH5
    - type: data
      text: Other task data
      link: http://doi.org/10.17639/nott.7274  
      
# Activity subspaces in mPfC   
- id: doi:10.1523/JNEUROSCI.1412-21.2022
  tags:
    - prefrontal-cortex
    - latent-dynamics

# Bayesian inference of connections between neurons
- id: doi:10.1523/jneurosci.1487-21.2021
  tags:
    - basal-ganglia
    - Bayesian
  buttons:
    - type: source
      text: Code
      link: https://github.com/Humphries-Lab/Bayesian-map-of-striatum-circuitry

# Spectral estimation for networks
- id: doi:10.1371/journal.pone.0254057
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/NetworkNoiseRejection

# weak-strong principles
- id: doi:10.51628/001c.24619
  tags:
    - latent-dynamics

# The Spike
- id: isbn:9780691195889
  tags:
    - latent-dynamics

# mPfC plastic irrespective of learning
- id: doi:10.1523/jneurosci.1370-17.2019
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/PfCDictionary

# Ensemble code in mPhfC
- id: doi:10.1038/s41467-018-04638-2
  tags:
    - prefrontal cortex
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/sibangi/PFCensemble_ITI

# Aplysia spiral attractor
- id: doi:10.7554/eLife.27342
  tags:
    - Aplysia
    - latent-dynamics
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/AplysiaAttractorAnalysis
    - type: data
      text: Data
      link: http://dx.doi.org/10.6080/K0SN074B

# Aplysia modular deconstruction
- id: doi:10.1016/j.neuron.2015.03.005
  tags:
    - Aplysia
    - latent-dynamics
  buttons:
    - type: source
      text: Code for paper
      link: https://github.com/mdhumphries/NeuralEnsembleAnalysis

# Prog Neurobiol cortical activity distributions
- id: doi:10.1016/j.pneurobio.2012.09.004
  tags:
    - latent-dynamics
  buttons:
    - type: paper
      text: Download paper
      link: research/Wohrer2013.pdf

# DA exploit-explore via BG
- id: pmid:22347155
  tags:
    - dopamine
    - basal-ganglia

# MNAS book chapter 
- id: doi:10.1017/CBO9780511731525.018
  tags:
    - reticular-formation
    - action-selection
  buttons:
    - type: paper
      text: Download paper
      link: research/Humphries2011a.pdf

# PLoS One small-world-ness
- id: doi:10.1371/journal.pone.0002051
  tags:
    - network-theory
  buttons:
    - type: package
      text: Code toolbox
      link: https://github.com/mdhumphries/SmallWorldNess 
      
# papers to remove from ORCID: bioRxiv versions of published papers

# motor cortex pre-print: uncomment once published in full
- id: doi:10.1101/2023.05.26.542452
  remove: true
  
- id: doi:10.1101/2022.08.30.505807
  remove: true

- id: doi:10.1101/2021.06.08.447507
  remove: true

- id: doi:10.1101/668962
  remove: true

- id: doi:10.1101/543678
  remove: true

- id: doi:10.1101/260992
  remove: true

- id: doi:10.1101/187948
  remove: true

- id: doi:10.1101/115485
  remove: true

- id: doi:10.1101/104562
  remove: true

- id: doi:10.1101/027102
  remove: true

- id: pmid:25819612
  remove: true
