name: Mirror to sysweb-site

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_KEY }}

      - name: Push to mirror
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add mirror git@github.com:hkruoft/sysweb-mirror.git
          # Create a temporary orphan branch
          git checkout --orphan temp
          git add -A
          git commit -m "Mirror snapshot"
          git push mirror temp:main --force
